### ISSUE TITLE
CCL April deliverable

### ISSUE THREAD

**Issue by cmutel** [OASES-project/CCL-results#1]
# Task list for April deliverable

- [x] Hybrid database with ecoinvent 3.9.1 and EXIOBASE 3.8.1
- [x] Define Monte Carlo calculation procedure sampling from real data on household population sample
- [x] Define and document output format for Monte Carlo results @cmutel 
- [x] Calculate results and produce data package for average household (GWP and UBP) @jakobsarthur 
- [x] Calculate results and produce data package for household archetypes (GWP and UBP) @jakobsarthur 
- [ ] Calculate results and produce data package for specific autos @cmutel 
- [x] Calculate results and produce data package for hospitals @cmutel 
- [x] Validation check: CO2 and CH4 production volumes @cmutel 
- [x] Document CO2 and CH4 validation check @cmutel 
- [x] Validation check: Mining production volumes @jakobsarthur 
- [x] Document mining validation check @jakobsarthur 
- [x] Document results for household types (GWP and UBP) @jakobsarthur
- [x] Start documentation markdown on github @jakobsarthur  
- [ ] Document plans for hybridization procedure revision @michaelweinold
- [x] Add final notebooks to this repository @cmutel @jakobsarthur

**Comment by michaelweinold** [comment]
> Document plans for hybridization procedure revision

@cmutel does this build on the two-pager I submitted a few weeks ago? What _exactly_ is expected?

**Comment by cmutel** [comment]
Please adapt and copy some more text from your research plan on what you plan to do in the next 1-2 years. Thanks!
